
#Better Invisibility Config Settings
[common]
	#Remove invisibility particles from other mobs (default:true)
	removeParticlesFromMobs = false
	#Invisibility effect removed when discovered by Mobs (default:true)
	discoveryRemovesInvisibility = true
	#Show invisiblity potion particles (default:false)
	showParticles = false
	#Invisibility effect removed if Player attacks (default:true)
	attackRemovesInvisibility = true
	#Invisiblity detection distance (default: 3)
	#Range: 1 ~ 10
	proximityDetectionDistance = 3
	#Show armor and weapons when invisible (default:false)
	showArmorWeapons = false
	#Invisible to Mob AI when invisible (default:true)
	invisibleToMobs = true
	#Mod sounds on (default:true)
	soundsOn = true
	#Can sneak by mobs when inside detection distance (default:true)
	sneakWhenClose = true
	#Player loses sight when invisible (default:false)
	blindWhenInvisible = false
	#Radius of Invisibility Effect (default: 30)
	#Range: 1 ~ 100
	invisibilityRadius = 30

